Выполнил второе задание
htmlacademy-htmlcss/21780-technomart-31 pull request #2
Opened 2021-05-25 18:12 UTC by KollegOFF

2021-05-25 21:24 UTC, PolinaShneider commented on index.html
> +            <a href="#">Войти</a>
Зачем ты столько элементов помещаешь в один li? В чем тогда смысл использования списка? По поводу CSS не переживай — лишние буллеты списка уберешь в одной из следующих домашек

2021-05-25 21:24 UTC, PolinaShneider commented on index.html
> +            <a href="#">Контакты</a>
Здесь та же история. Должно быть `ul` > `li` > `a` (в каждом li одна ссылка)

2021-05-25 21:24 UTC, PolinaShneider commented on index.html
> +            <p>Перфораторы</p>
Мб, это заголовок?

2021-05-25 21:24 UTC, PolinaShneider commented on index.html
> +            Материалы <a href="#">на любой вкус</a>
Возможно, "Материалы", "Инструмент" и т. д. стоит оформить заголовками третьего уровня. Как думаешь?

2021-05-25 21:25 UTC, PolinaShneider commented on index.html
> +            <p>Перфораторы</p>
Выглядит как заголовок третьего уровня. У "Перфораторы"  и "Настоящие мужские игрушки" немного разный смысловой акцент. Первое озаглавливает понятие, второе его дополняет

2021-05-25 21:27 UTC, PolinaShneider commented on index.html
> +        <dl>
Это вам показывали на лекции? Почему здесь обычный ul li не подходит?

2021-05-25 21:31 UTC, PolinaShneider commented on index.html
> +          Настоящий мужской шоппинг начинается здесь! Огромный выбор товаров для<br>
Рекомендую избавиться от br и не использовать их вообще, пока не дойдешь до окончательной стилизации pixel perfect. Когда ты начнешь работать со стилями, ты укажешь ширину — это поможет решить большую часть проблем с переносами.

А еще br — немного боль при мобильной верстке. У вас на интенсиве ее не будет, но держать этот момент в голове полезно

2021-05-25 21:37 UTC, PolinaShneider requested changes
Есть пара вопросов / замечаний

2021-05-27 15:40 UTC, KollegOFF commented on index.html
> +            <a href="#">Войти</a>
Плохо накопировал просто 😄

2021-05-27 15:40 UTC, KollegOFF commented on index.html
> +            <p>Перфораторы</p>
Поменял на заголовок, но мне кажется, выглядит немного натянуто.

2021-05-27 15:43 UTC, KollegOFF commented on index.html
> +        <dl>
На лекции вроде не было, в материалах был.
Открыл для себя новый элемент, пытаюсь найти ему применение.
Здесь выбрал его, потому что на мой взгляд здесь есть связь понятие - описание.

2021-05-27 15:43 UTC, KollegOFF commented on index.html
> +          Настоящий мужской шоппинг начинается здесь! Огромный выбор товаров для<br>
Удалил все `br`-ы.

2021-05-27 18:43 UTC, PolinaShneider commented on index.html
> +            <p>Перфораторы</p>
Представь свою верстку без стилей (хотя она и так у тебя сейчас в таком виде). Ты должен без стилей понять структуру сайта. Пойнт в том, что "Перфораторы" — это один из подразделов, а "Настоящие мужские игрушки" — уже его описание.

Я не настаиваю, и это мнение ни в коем случае не единственно правильное. Просто стараюсь объяснить свою мысль

2021-05-27 18:50 UTC, PolinaShneider commented on index.html
> +        <dl>
Окей) Как по мне, это экзотика, и ul li здесь за глаза хватит. Но какого-то нарушения семантики здесь нет, поэтому пусть будет :)

2021-05-27 18:50 UTC, merged