Выполнил девятое задание
htmlacademy-htmlcss/21780-technomart-31 pull request #9
Opened 2021-07-13 20:35 UTC by KollegOFF

2021-07-13 22:13 UTC, PolinaShneider commented on index.html
>        </section>
![image](https://user-images.githubusercontent.com/15448200/125531893-dcc3bc14-97a7-4043-963b-744bf305fb4d.png)

Этого **нет** в макете. Помнишь, мы добавляли элементы для семантики (ну чтоб поисковые роботы лучше индексировали) — для пользователя подобные элементы надо визуально скрыть

2021-07-13 22:13 UTC, PolinaShneider commented on index.html
Нет выравнивания по вертикали
![image](https://user-images.githubusercontent.com/15448200/125532026-52177a7e-03db-4047-a57f-c092abf439e4.png)

2021-07-13 22:15 UTC, PolinaShneider commented on index.html
>        <section class="popular-products">
У тебя в макете эти блоки более вытянуто-прямоугольные (соотношение длин сторон другое) — проверь, пожалуйста

![image](https://user-images.githubusercontent.com/15448200/125532121-d806a1ff-5f86-4f3a-8b0c-ad09e6a44dd7.png)

2021-07-13 22:16 UTC, PolinaShneider commented on index.html
> +        <div class="header-wrapper">
![image](https://user-images.githubusercontent.com/15448200/125532224-b683c0b7-ec18-44c6-a034-480dcdbc702e.png)

Элементы меню должны быть в ряд

2021-07-13 22:17 UTC, PolinaShneider requested changes
На этапе создания более мелкой сетки на flex-ах страница должна очень сильно напоминать макет. Сейчас у тебя выравнивание и размеры блоков сильно отличаются. Доделай, пожалуйста

2021-07-14 06:47 UTC, KollegOFF commented on index.html
>        </section>
Планирую скрыть всё лишнее в следующем задании.

2021-07-14 06:49 UTC, KollegOFF commented on index.html
>        <section class="popular-products">
Тут пока только общая сетка на гридах, в следующем задании планирую доделать.

2021-07-14 07:13 UTC, merged